server:
  port: 7010
spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active: native  # 配置使用本地储存
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/ # 搜索src/main/resource 下的propertie
        git:
          uri: https://gitee.com/car-express/pro-config.git #配置文件所在仓库
          default-label: master #配置文件分支
          search-paths: pro-config  #配置文件所在根目录										文件夹下的文件
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/